Karafecho patch 1
NCATS-Tangerine/FHIR-PIT pull request #20
Opened 2024-04-16 15:42 UTC by karafecho

Finalizing text for CHORDS chapter.

2024-04-16 20:00 UTC, hyi requested changes
@karafecho @jjgarciac I took a look at the PR and left some comments for your consideration.

2024-04-16 20:00 UTC, hyi commented on tutorial/10-FHIRPIT.Rmd
> +| title: "FHIR PIT: HL7 Fast Healthcare Interoperability Resources Patiend data Integration Tool" |
typo correction: Patiend->Patient

2024-04-16 20:00 UTC, hyi commented on tutorial/10-FHIRPIT.Rmd
> +The patient dataset used in this tutorial is synthetic. When using actual patient or participant data containing Protected Health Information (PHI), one must run FHIR PIT within a secure enclave and
Since we actually have multiple patient data files, I am wondering it might fit better to use "datasets" in plural form?

2024-04-16 20:00 UTC, hyi commented on tutorial/10-FHIRPIT.Rmd
> +
This sentence ```To support multiple healthcare visits, FHIR PIT vectorizes the FHIR patient records by grouping daily FHIR domains (e.g., Condition, Laboratory, Medication, Procedure) and counting them.``` might need a bit of clarification. Does it mean FHIR PIT vectorized the FHIR patient records by grouping and counting FHIR data ( (e.g., Condition, Laboratory, Medication, Procedure) on a daily basis?

2024-04-16 20:00 UTC, hyi commented on tutorial/10-FHIRPIT.Rmd
> +* [US Census Bureau American Community Survey (ACS) socio-economic exposures data](https://www.census.gov/programs-surveys/acs/data.html) - The US Census Bureau's ACS is a 5-year survey sample from t
Add ```that``` before ```are available, including survey estimates on...```?

2024-04-16 20:00 UTC, hyi commented on tutorial/10-FHIRPIT.Rmd
> +This tutorial demonstrates how to execute FHIR PIT and analyze its output. The patient dataset used in this tutorial is synthetic and intended for demostranstion purposes only. The environmental data
typo correction: ```demostranstion``` to ```demonstration```

2024-04-16 20:00 UTC, hyi commented on tutorial/10-FHIRPIT.Rmd
> +This tutorial demonstrates how to execute FHIR PIT and analyze its output. The patient dataset used in this tutorial is synthetic and intended for demostranstion purposes only. The environmental data
Change ```To add data, please update the 'data/FHIR/all' directory``` to ```To add your own data, please update the 'data/input' directory```?

2024-04-17 13:55 UTC, karafecho reviewed
Incorporated Hong's suggestions.

2024-04-17 13:55 UTC, karafecho commented on tutorial/10-FHIRPIT.Rmd
> +| title: "FHIR PIT: HL7 Fast Healthcare Interoperability Resources Patiend data Integration Tool" |
Fixed.

2024-04-17 13:55 UTC, karafecho commented on tutorial/10-FHIRPIT.Rmd
> +The patient dataset used in this tutorial is synthetic. When using actual patient or participant data containing Protected Health Information (PHI), one must run FHIR PIT within a secure enclave and
Accepted suggestion.

2024-04-17 13:55 UTC, karafecho commented on tutorial/10-FHIRPIT.Rmd
> +
Clarified the text.

2024-04-17 13:55 UTC, karafecho commented on tutorial/10-FHIRPIT.Rmd
> +* [US Census Bureau American Community Survey (ACS) socio-economic exposures data](https://www.census.gov/programs-surveys/acs/data.html) - The US Census Bureau's ACS is a 5-year survey sample from t
Clarified the text.

2024-04-17 13:55 UTC, karafecho commented on tutorial/10-FHIRPIT.Rmd
> +This tutorial demonstrates how to execute FHIR PIT and analyze its output. The patient dataset used in this tutorial is synthetic and intended for demostranstion purposes only. The environmental data
Fixed typo and accepted suggested text.

2024-04-17 13:59 UTC, hyi approved these changes

2024-04-17 14:02 UTC, merged